### ISSUE TITLE
Corrupt output file for many signals

### ISSUE THREAD

**Issue by jcfschulz** [danielhrisca/asammdf#54] opened 2018-03-19 18:56 UTC
Hi, 
I just upgraded from version 2.8.0 to 3.2.1. I am now getting a corrupt output mf4, if there are to many signals in the file. I attach a minimal example, where this happens. I am using Python 2.72. 

When I have 75 Signals in this example, everything is working fine, from 76 on, all channels including the time channel are corrupted, approximately half of the channel data is 0. I am fairly new to this library, I could not really see, where the issue is coming from...
 
```

import asammdf
import numpy as np

timestamps2 = np.arange(30.02,305.47,0.02)
signals = []
for i in range(76):
    signals.append( asammdf.Signal(samples=np.ones(len(timestamps2)), timestamps=timestamps2, name="number %d"%i) )
    
mdf4 = asammdf.MDF(version='4.10',memory="minimal")
mdf4.append(signals, 'Created by Python')
mdf4.save('weird.mf4', overwrite=True)

new = asammdf.MDF("weird.mf4")
new.get("number 1").timestamps

```

Greetings, Julius

**Comment by jcfschulz** [comment] 2018-03-19 19:01
If it helps, I just realised, it's the memory="minimal" that causes the trouble. 
It was working in the previous version though. Would be really great, if there is a way to fix this, because I tend to have somewhat large mdf from time to time :)

**Comment by danielhrisca** [comment] 2018-03-19 19:24
Hello Julius,

the problem is actually that the _memory_ argument is not validated: it should be _full_, _low_ or _minimum_ but you have supplied _minimal_ (check out the documentation http://asammdf.readthedocs.io/en/master/api.html#mdf4). I'll include a fix for this in the development branch.

In the mean time use the proper argument value and it will work fine (I've worked with files containing 60000 channels)

**Comment by jcfschulz** [comment] 2018-03-20 07:41
Hello Daniel,
thanks for this quick reply. What a stupid mistake by me, I would not have guessed that from the behaviour. Sorry for bringing this up.

**Comment by jcfschulz** [comment] 2018-03-28 15:29
Hi Daniel,
sorry for the late response, this fix works fine.
Thank you, Greetings Julius

**Closed** 2018-04-03 13:07 UTC
Labels: Fixed - waiting for next release
