### ISSUE TITLE
Cut feature on Modify & Export tab does not work

### ISSUE THREAD

**Issue by MartinAl1337** [danielhrisca/asammdf#563] opened 2021-08-27 17:15 UTC
When trying to use the cut feature on a visualized MF4 file, the program will always run into the same error. Error trace received in the error window:
2021-08-27, 10:13:29
--------------------------------------------------------------------------------
<class 'Exception'>	 
Traceback (most recent call last):
  File "asammdf\gui\utils.py", line 381, in run
  File "asammdf\mdf.py", line 824, in cut
  File "asammdf\blocks\mdf_v4.py", line 3438, in append
  File "<__array_function__ internals>", line 6, in packbits
TypeError: Expected an input array of integer or boolean data type

--------------------------------------------------------------------------------
  File "asammdf\gui\widgets\file.py", line 2249, in apply_processing
  File "asammdf\gui\utils.py", line 346, in run_thread_with_progress

Error window that appears when trying to cut the MF4 file is attached.
![Error when trying to cut](https://user-images.githubusercontent.com/89657214/131164716-f8b8ad37-e124-4613-8c05-947cf6e050b2.PNG)

**Comment by MatinF** [comment] 2021-08-28 17:47
Hi Daniel - I can confirm that this happens for DBC decoded MF4 log files. It seems to work as intended for raw bus logging MF4 files though.

**Comment by danielhrisca** [comment] 2021-08-29 19:12
Hello, please try the latest development branch code

**Comment by MatinF** [comment] 2021-08-30 17:12
Seems to be resolved with your dev fix Daniel, thanks

**Comment by MatinF** [comment] 2021-09-02 17:07
If it’s possible to do a patch release with this that would be great!

**Comment by danielhrisca** [comment] 2021-09-03 17:52
I've merged a big change switching from a list to a tree in the plot channel selection. Users can now create channel groups using right mouse click. Maybe you can give it a run to make sure it works correctly

**Comment by MatinF** [comment] 2021-09-04 18:10
Hi Daniel, from a quick review it looks to work quite well with the channel groups from my perspective in 6.4.0dev6

**Closed** 2021-09-06 06:05 UTC
