### ISSUE TITLE
Concatenate list of ByteIOs

### ISSUE THREAD

**Issue by StefanWolf-tp** [danielhrisca/asammdf#466] opened 2021-01-19 12:28 UTC
# Python version
'python=3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]'
'os=Windows-10-10.0.18362-SP0'
'numpy=1.19.2'
'asammdf=6.0.1'
# Code 

  ## MDF version
MDF 4
  
# Description
I have to do some calculations with mdf files. The files are present in two types:
- compressed mdf file
- compressed in gz

now i read the docs and found that the parameter 'name' for the constructor of a MDF object can also be a BytesIO (file like object).
After testing it works for one single file:

```python
import asammdf
import gzip

zip_file = gzip.open('D:/processfolder/2019-12-03T21_36_48Z.mf4.gz')
test_mdf = asammdf.MDF(zipfile)
test_mdf.channels_db
Out[23]: 
{'Time': ((0, 0),),
 'WET-999_Antrieb_R': ((0, 1),),
 'WET-999_Pump_L': ((0, 2),),
 'WET-998_Antrieb_L': ((0, 3),),
 'WET-998_Antrieb_R': ((0, 4),)}
```

but i also have to do some calculations with a longer time interval - so i have to concatenate them. With the compressed mdf files it works with a given list of the paths. But this doesn't works with a list of the GzipFiles (bytesIO).

```python
zip_file2 = gzip.open('D:/processfolder/2019-12-03T21_37_08Z.mf4.gz')
zippedFiles = [zip_file, zip_file2]
conc_mdf = asammdf.MDF.concatenate(zippedFiles, sync=False)
```

> Traceback (most recent call last):
> 
>   File "<ipython-input-13-a8f26d6dc301>", line 1, in <module>
>     fusionmdf = asammdf.MDF.concatenate(zippedFiles, sync=False)
> 
>   File "D:\Users\de007\Anaconda3\lib\site-packages\asammdf\mdf.py", line 1662, in concatenate
>     with open(file, "rb") as mdf:
> 
> TypeError: expected str, bytes or os.PathLike object, not GzipFile
> 

Is there maybe a possibility to concatenate multiple files from the ram? I have many TB of gz - compressed files and want to avoid decompressing and saving as compressed mf4 file.

Greetings

**Comment by danielhrisca** [comment] 2021-01-19 13:49
Hello Stefan,

I've pushed fixes to the development branch so your code should work now, but I'm afraid it will run very slow since doing random reads in the zipped file is slow.

**Comment by danielhrisca** [comment] 2021-01-19 15:20
Also see https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.concatenate

**Comment by StefanWolf-tp** [comment] 2021-01-19 16:23
hey,

thanks! I just tested the dev branch and it seems to work fine. I can understand your consider on accessing the zipped files so i did some kind of 'performance' testing.
In the test i concatenate 15 mdf4 files with 20sec sensor data 4 channels and 40kHz samplerate each.
I saved the files in 3 different ways:
- gzipped
- mdf compressed (save - compression level 2)
- mdf uncompressed (raw)  (


```
Total ellapsed time for gzipped files: 5.072899341583252 sec
Total ellapsed time for compressed files: 5.233855485916138 sec 
Total ellapsed time for raw files: 2.752368450164795 sec
```

**Comment by danielhrisca** [comment] 2021-01-19 16:35
> hey,
> 
> thanks! I just tested the dev branch and it seems to work fine. I can understand your consider on accessing the zipped files so i did some kind of 'performance' testing.
> In the test i concatenate 15 mdf4 files with 20sec sensor data 4 channels and 40kHz samplerate each.
> I saved the files in 3 different ways:
> 
> * gzipped
> * mdf compressed (save - compression level 2)
> * mdf uncompressed (raw)  (
> 
> ```
> Total ellapsed time for gzipped files: 5.072899341583252 sec
> Total ellapsed time for compressed files: 5.233855485916138 sec 
> Total ellapsed time for raw files: 2.752368450164795 sec
> ```

This is "low" data. I was testing with 40000 channels and I had to stop the process when reading directly from the gzip object. Again, the problem is with reading the file not with saving it.

**Comment by StefanWolf-tp** [comment] 2021-01-20 07:32
sorry i was not clear.

my timings where all reading the files. i saved the same files in 3 different ways to work/load the same data.

i dont have files to validate/test the huge channel count. In my case i have less channels but many samples per channel (like i wrote 40kHz per channel). So the uncompressed files have a size of about 275MB (~18,8 MB each).

**Comment by danielhrisca** [comment] 2021-01-20 08:34
with the benchmark file (184MB with ~36000 channels)

* uncompressed: 4.8s
* compression =2 : 4.9s
* gzip expanded in BytesIO : 6.9s
* gzip random io : estimated 2 hours

**Closed** 2021-01-26 14:05 UTC
