### ISSUE TITLE
Converting large files

### ISSUE THREAD

**Issue by Nimi42** [danielhrisca/asammdf#152] opened 2019-03-29 16:02 UTC
When converting large files to parquet or a Pandas Dataframe, I Always get a Memory
error. I was wondering, if it is possible to have some kind of low Memory mode or even better Streaming mode.

Essentially I want parquet files, but I saw that asammdf converts the .dat, mf4 etc... files to 
a Pandas DataFrame under the Hood anyway and uses the result to export to Parquet.

So I was playing around with the Code trying to cast the columns to more appropriate dtypes.

```python
def _downcast(self, src_series):
    if np.issubdtype(src_series.dtype, np.unsignedinteger):
        res_series = pd.to_numeric(src_series, downcast='unsigned')
    elif np.issubdtype(src_series.dtype, np.signedinteger):
        if src_series.min() < 0:
            res_series = pd.to_numeric(src_series, downcast='signed')
        else:
            res_series = pd.to_numeric(src_series, downcast='unsigned')
    elif np.issubdtype(src_series.dtype, np.floating):
        res_series = pd.to_numeric(src_series, downcast='float')
    else:
        res_series = src_series.astype('category')

    return res_series
```

It saves some memory, but unfortunately this is not enough. I do have some files that are 5Gb or larger. When converted to a DataFrame they get inflated to beyond 20Gbs.

Any help is appreciated.

**Comment by danielhrisca** [comment] 2019-03-29 16:25
Hello @Nimi42 ,

I will have a look at this over the week-end. The dstaframe aproach was quick and convenient, I'm sure we can get a significant memory usage at the expense of slower execution performance

**Comment by danielhrisca** [comment] 2019-03-29 17:25
@Nimi42 It looks like the parquet format is not friendly towards adding new columns/channels https://github.com/dask/fastparquet/issues/244

**Comment by danielhrisca** [comment] 2019-03-30 14:46
@Nimi42 
I've added the argument _reduce_memory_usage_ to _to_dataframe_ . 

results on my test file:

|Convert to pandas.DataFrame                       |Time [ms]|RAM [MB]|
|--------------------------------------------------|---------|--------|
|asammdf 5.3.0.dev0 reduce=True                    |    12977|    1925|
|asammdf 5.3.0.dev0 reduce=False                   |    13852|    3140|

**Comment by danielhrisca** [comment] 2019-03-30 18:31
@Nimi42 

I've made some improvements to the _export_ method:

* you can use compression for the output (see  _compression_ keyword argument https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.export)
* _reduce_memory_usage_ argument was added to the _export_ method and can be used with ``parquet`` and if _single_time_base_ argument is _True_

**Comment by Nimi42** [comment] 2019-04-01 15:06
Wow... You're damn quick.

I've been researching a bit over the Weekend and I found the following resources.
Not sure if this is a viable solution though. 

First one is an issue on the fastparquet GitHub https://github.com/dask/fastparquet/issues/72. If I understand this correctly, it might still be possible to write massive files.

Second one is a Question (and answer) on stackoverflow. It uses pyarrow though. I think pyarrow is
going to include Streaming soon or already, but the proposed answer splits it into a Collection of many files, which is ok for parquet files. https://stackoverflow.com/questions/46157709/converting-hdf5-to-parquet-without-loading-into-memory

**Comment by danielhrisca** [comment] 2019-04-01 15:09
Do you still get memroyerror with the new code?

**Comment by Nimi42** [comment] 2019-04-01 15:30
@danielhrisca 

Did not try yet. But I have some files here that are About 4 Gb in size, which were inflated to over 20 Gbs and I have another one, which is 8 Gb in size. I did not even try that one yet.

Since you can optimise the Performance at the appropriate Level this might already be enough. I just wanted to throw in some Option. I will definitely try your new Version out first.

cheers

**Comment by danielhrisca** [comment] 2019-04-01 15:39
I will look into them it would be a lot better if we could add the chsnnels secvebtially to the parquet file

**Comment by Nimi42** [comment] 2019-04-02 14:11
I've tested the new Code. It's about as Memory efficient as my work around, but faster.

**Comment by Nimi42** [comment] 2019-04-02 14:14
The development Version does indeed work without Problems. I noticed though, that asammdf includes the device Name for .dat files, but not for .mf4. Does that have specific reason? I'd rather have it consistent to be honest or optional, because I don't need the device Name.

**Comment by Nimi42** [comment] 2019-04-03 09:02
Ok... the datatypes are not that big of a problem. Once I have the dataframe in pyarrow i can easily do it myself, since pyarrow is very memory efficient. Thanks again for the reduce memory option.

**Comment by Nimi42** [comment] 2019-04-03 09:16
I can convert the respective columns by manually with pyarrow afterwards, so I guess that's left for me to handle.

**Comment by legout** [comment] 2019-04-03 09:42
> I will look into them it would be a lot better if we could add the channels sequentially to the parquet file

Hi Daniel,

as you already know, I also had/have memory problems loading large mdf-files into pandas dataframes. Therefore I was playing around with pyarrow last week. I ended up, with a function that converts the data/samples of all channels  of a data group into a pyarrow table. This table can be written to parquet files (one for each data group if not using a unique timebase) easily, without the memory issues.

Furthermore, converting this pyarrow tables to a pandas dataframe is also very fast and memory friendly.

I´ll post my function here next week, when I am back from holidays. However, implementing this is straight forward, so maybe you already realized it on your own.

Regards,
legout

**Comment by danielhrisca** [comment] 2019-04-03 09:50
Hello @legout ,

my concern was indeed related to the single_time_base functionality.

**Comment by Nimi42** [comment] 2019-04-03 09:53
I must admit that I do not understand the MDF Format very well. What is a data group? All Signals with a common time base?

**Comment by danielhrisca** [comment] 2019-04-03 09:56
MDF is designed to handle signals with different sampling rates. Inside a channel group all the channels have the same timebase. 

Parquet as far as I see is designed for signals with the same sampling rate. This is why it is difficult to export a MDF file that may contain different sampling rates, to parquet.

**Comment by legout** [comment] 2019-04-03 09:57
> Hello @legout ,
> 
> my concern was indeed related to the single_time_base functionality.
Hi Daniel,

when using single_time_base, there will be only one pyarrow table. Adding columns/channels to this table and/or writing the that table or just some columns/channels to a parquet file is possible.

**Comment by Nimi42** [comment] 2019-04-03 10:04
Multiple parquet files for one mdf file are definitely a valid use case, as Long as it is possible to roughly control the the size of each chunk.

**Comment by danielhrisca** [comment] 2019-04-03 10:05
This still means that you have to hold the table in memory until all columns are ready, before writing the parquet file, isn't it? Can you write new columns to an existing parquet file/folder structure?

**Comment by Nimi42** [comment] 2019-04-03 10:09
I guess it would be to complicated to read the MDF file partially in terms of rows. and write multiple parquet files?

**Comment by legout** [comment] 2019-04-03 10:12
Yes. The table is still in memory. However, using pandas to write the data to parquet produces a lot of overhead. Therefore, using pyarrow is much more memory friendly.

**Comment by danielhrisca** [comment] 2019-04-03 10:15
Ok, I will have a crack at this

**Comment by legout** [comment] 2019-04-03 10:15
> I guess it would be to complicated to read the MDF file partially in terms of rows and write multiple parquet files? (When using a **single time base** for **all columns**)

I think this won´t reduce memory usage, as mentioned by daniel,  because even when splitting the table into several row groups for writing, you have to hold the whole table in memory.

**Comment by Nimi42** [comment] 2019-04-03 10:19
> I think this won´t reduce memory usage (when using pyarrow), because even when splitting the table into several row groups for writing, you have to hold the whole table in memory (as mentioned by daniel).

Right... but there is a method called cut. I thought something along the lines of loading the MDF file partially and then writing out a parquet file then loading the next part of the MDF file and creating another Parquet file with the same Schema. For Frameworks like spark it shouldn't make a difference.

**Comment by danielhrisca** [comment] 2019-04-03 10:21
This would hurt performance a lot

**Comment by legout** [comment] 2019-04-03 10:27
> > I think this won´t reduce memory usage (when using pyarrow), because even when splitting the table into several row groups for writing, you have to hold the whole table in memory (as mentioned by daniel).
> 
> Right... but there is a method called cut. I thought something along the lines of loading the MDF file partially (not necessarily with the cut method. I just want to illustrate my point) and then writing out a parquet file then loading the next part of the MDF file and creating another Parquet file with the same Schema. For Frameworks like spark it shouldn't make a difference.
> 
> In the ideal case, you'd be able to create parquet files of a particular chunk size.

What do you wanna do with that chunked parquet files? Loading all data from the parquet file into a pandas dataframe? If so, you´ll have the same memory issues as before.

**Comment by Nimi42** [comment] 2019-04-03 10:28
> This would hurt performance a lot

That's too bad. Unfortunately, I do have MDF files that do not fit into memory as a whole. So I can't think of any other way.

Is it possible to somehow get the start and stop values of a unified time base? Then I'd implement my own function using cut.

**Comment by Nimi42** [comment] 2019-04-03 10:30
> What do you wanna do with that chunked parquet files? Loading all data from the parquet file into a pandas dataframe? If so, you´ll have the same memory issues as before.

Machine learning and analysis with spark

**Comment by legout** [comment] 2019-04-03 10:42
Than i´ll suggest splitting the mdf-files into "column"-chunks using mdf.select instead of splitting into "row"-chunks. Writing this into "column"-chunks into parquet files and concatenate the data into one spark dataframe inside the cluster.

**Comment by Nimi42** [comment] 2019-04-03 10:51
> Than i´ll suggest splitting the mdf-files into "column"-chunks using mdf.select instead of splitting into "row"-chunks. Write this "column"-chunks into parquet files and concatenate the data into one spark dataframe inside the cluster.

That should work. I'll try that for now.

**Comment by Nimi42** [comment] 2019-04-03 12:30
Now that I think about it... it would work. If take a number of channels and convert them to parquet, they would not havt the sam time base.

I guess it would be easy to calculate a unified time base and use it to convert a subset of channels to parquet, but at the moment asammdf does not provide a method to get this unified time base….

and more importantly use it to convert this subset.

**Comment by legout** [comment] 2019-04-03 12:43
You can calculate it on your own. 

```
mdf = asammdf.MDF('file.mf4')
channels = list(mdf.channels_db.keys()) # replace this by a list of channels if not all channels should be used
raster = 0.1 # you can also use a specific channel name

ch_grp_idx = defaultdict(list)
for channel in channels:
    grp, idx = mdf.channels_db[channel][0]
    ch_grp_idx[grp].append([channel, grp, idx])

if isinstance(raster, str):
    grp, idx = mdf.channels_db[raster][0]
    timeNew = smdf.get(group=grp, index=idx).timestamps
else:
    tmin = []
    tmax = []
    grp_idx = []
    for grp in ch_grp_idx:
        idx = self._mdf.masters_db[grp]
        grp_idx.append([None, grp, idx])
    signals = mdf.select(grp_idx)
    for signal in signals:
        if len(signal.samples) != 0:
            tmin.append(signal.samples.min())
            tmax.append(signal.samples.max())
    timeNew = np.arange(np.min(tmin), np.max(tmax) + raster, raster)

if time_from_zero:
    timeNew = np.round(timeNew-timeNew[0], 3)
else:
    timeNew = np.round(timeNew, 3)
```

**Comment by Nimi42** [comment] 2019-04-03 14:03
@legout 

That is true, but the to_dataframe method das not allow me to use my own time base. I can hack it into the library, but the api atm is not built for such a use case.

But thanks for the code.  I'll use it as work around for now.

**Comment by Nimi42** [comment] 2019-04-04 12:10
@legout @danielhrisca 

Thanks guys. I probably shouldn't use the thread to do this, but I just wanted to thank you for you help.
I 've played around with your suggestions and have now a reliable way to convert large dat files to parquet.

**Comment by legout** [comment] 2019-04-04 13:27
No Problem. 
If you don´t mind, can you share your code with me/us?

**Comment by Nimi42** [comment] 2019-04-04 15:12
@legout 
Of Course. I just want to clean it up if that's ok.

**Comment by Nimi42** [comment] 2019-04-04 17:26
@legout 

Here is the Code, but I warn you. It's slightly complicated and not very performant because the files have to be split based on the column and joined spark.

```python
import os
from functools import reduce
from natsort import natsorted

import numpy as np
import pandas as pd

import asammdf as asam

import pyarrow as pa
import pyarrow.parquet as pq
from pyspark.sql import SparkSession
from pyspark.sql import SQLContext

from metadata import Datenstandsbezeichnung


class DatToParquet:

    def __init__(self, num_channels=1500):
        self.num_channels = num_channels

    def toParquet(self, mdf, parquet_path):
        """
        Convert the given mdf file into multiple parquet files divided by columns (depending on num_channels).

        :param mdf:
        :type mdf: asam.MDF
        :param parquet_path:
        :type parquet_path: str
        :return:
        :rtype None
        """
        time_base = self._unfied_time(mdf, 0.1)

        mdf.configure(integer_interpolation=0)
        os.makedirs(parquet_path)

        for i, channels in enumerate(self._channel_gen(mdf)):
            chunk = mdf.filter(channels)
            df = chunk.to_dataframe(raster=0.1, master=time_base)
            del chunk
            self._remove_device_name(df)

            table = self._to_pyarrow(df)
            parquet_writer = pq.ParquetWriter(parquet_path + str(i) + '.parquet',
                                              table.schema,
                                              compression='snappy')
            del df
            parquet_writer.write_table(table)

    def _channel_gen(self, mdf):
        """
        Generates num_channel columns at a time to iterate through the mdf file in chunks.

        :param mdf:
        :type mdf: asam.MDF
        """
        result = []
        for i, signal in enumerate(mdf, 1):
            result.append(signal.name)
            if i % self.num_channels == 0:
                yield result
                result = []
        yield result

    @staticmethod
    def _remove_device_name(df):
        """
        Remove the device name from the column name to have consistent column names between .mf4, .dat, etc.

        !!! Renaming is done inplace

        :param df:
        :type df: pd.DataFrame
        :return: The renaming is done inplace
        :rtype None
        """
        lsthdr = list(df)
        for ii in range(len(lsthdr)):
            lsthdr[ii], b, c = lsthdr[ii].partition('\\')
        df.columns = lsthdr

    @staticmethod
    def _unfied_time(mdf, raster):
        """
        Calculate a unified time base for all signals. The code snippet has bin taken from asammdf.mdf.to_dataframe.

        :param mdf:
        :type mdf: asam.MDF
        :param raster:
        :type raster: float
        :return: A numpy array with the specified raster from start to stop
        :rtype np.array
        """
        masters = [mdf.get_master(i) for i in range(len(mdf.groups))]
        master = reduce(np.union1d, masters)

        if raster and len(master):
            if len(master) > 1:
                num = float(np.float32((master[-1] - master[0]) / raster))
                if num.is_integer():
                    master = np.linspace(master[0], master[-1], int(num))
                else:
                    master = np.arange(master[0], master[-1], raster, dtype=np.float64)
        return master

    @staticmethod
    def _to_pyarrow(df):
        """
        Cast unsigned values to signed because spark can't handle unsigned values.

        :param df:
        :type df: pd.DataFrame
        :return:
        :rtype pa.table
        """
        table = pa.Table.from_pandas(df)

        for i in range(table.num_columns):
            col = table.column(i)
            if col.type == pa.uint8():
                col = col.cast(pa.int16())
                table = table.set_column(i, col)
            elif col.type == pa.uint16():
                col = col.cast(pa.int32())
                table = table.set_column(i, col)
            elif col.type == pa.uint32():
                col = col.cast(pa.int64())
                table = table.set_column(i, col)

        return table


class ToHDFS:

    def __init__(self, hdfs_path, master='local'):
        self.spark = SparkSession.builder \
            .master(master) \
            .appName('Test') \
            .config("spark.cores.max", "4") \
            .getOrCreate()

        self.sc = self.spark.sparkContext
        self.sqlContext = SQLContext(self.sc)

        self.path = hdfs_path

    def fromlocal(self, path, metadata):
        """
        Write a parquet file from local disk to hdfs store. If the file has been converted with the convert
        method than you need to provide the parent directory. Spark will join the split tables and partition them
        depending

        :param path:
        :type path: str
        :param metadata:
        :type metadata: Datenstandsbezeichnung
        """
        if os.path.isdir(path):
            files = os.listdir(path)
            files = natsorted(files)
            files = [path + file for file in files if file.endswith('.parquet')]
            size = sum([os.path.getsize(file) for file in files])
        elif os.path.isfile(path):
            size = os.path.getsize(path)
            files = [path]
        else:
            raise FileNotFoundError(path)

        gigaByte = 1e+9
        num_partition = int(size // gigaByte) + 1

        dataframes = [self.sqlContext.read.option('compression', 'snappy').parquet(file) for file in files]
        merge = reduce(lambda a, b: a.join(b, 'time'), dataframes)

        path = metadata.karosserie \
               + '/' + metadata.baustufe \
               + '/' + metadata.leistungsklasse \
               + '/' + metadata.schiene \
               + '/' + metadata.version
        merge.coalesce(num_partition) \
            .write.option("parquet.block.size", 32 * 1024 * 1024) \
            .parquet(self.path + path)
```


You can replace `metadata` with the path you want to write your data to and the temporary Directory for the converted parquet will not be cleaned up atm.
You can use the Code like so:

```python
from convert import DatToParquet, ToHDFS
from metadata import Datenstandsbezeichnung
import asammdf as asam

import time

hdfs_path = 'hdfs://localhost:9000/data/audi/gen3evo3/'
base_path = '/home/nemo/Downloads/'
tmp_path = base_path + 'tmp/'
file_2 = '2019-02-02Überfahrt_Pontreisna_Stuttgart02.dat'

mdf = asam.MDF(base_path + file_2)

# converter = DatToParquet()
# converter.toParquet(mdf, tmp_path)

metadata = Datenstandsbezeichnung(mdf.header)

time.sleep(8)

hdfs_connect = ToHDFS(hdfs_path)
hdfs_connect.fromlocal(tmp_path, metadata)
```

**Comment by Nimi42** [comment] 2019-04-05 13:13
I should note that it is necessary to Change asammdf library Code to accept your own time base.

**Comment by legout** [comment] 2019-04-05 15:35
Hi Nimi42,

thanks so far. Can you contact me please, as it seems you did not make your E-Mail public.

Regards,
legout

**Comment by danielhrisca** [comment] 2019-04-06 20:34
> You can calculate it on your own.

A faster way to find the min and max timestamps is this  https://github.com/danielhrisca/asammdf/blob/development/asammdf/mdf.py#L2468

**Comment by danielhrisca** [comment] 2019-04-06 20:41
> hat is true, but the to_dataframe method does not allow me to use my own time base. I can hack it into the library, but the api atm is not built for such a use case (is what I am getting at).

I will implement something similar to the new _resample_ method for _to_dataframe_ as well https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.resample

**Comment by Nimi42** [comment] 2019-04-08 07:21
> @Nimi42
I've made some improvements to the export method:
you can use compression for the output (see compression keyword argument https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.export)
reduce_memory_usage argument was added to the export method and can be used with parquet and if single_time_base argument is True

I took a look at the Code. If I understand correctly the savings are just numerical types. Another big Memory save I got was from using the pandas categorical type for objects. I have a lot of columns in my data that are composed of repeated strings. That might not be the case for anybody, but an Approach like the following might be interesting. 

https://www.dataquest.io/blog/pandas-big-data/

> We’ll write a loop to iterate over each object column, check if the number of unique values is less than 50%, and if so, convert it to the category type.

```python
for col in gl_obj.columns:
    num_unique_values = len(gl_obj[col].unique())
    num_total_values = len(gl_obj[col])
    if num_unique_values / num_total_values < 0.5:
        converted_obj.loc[:,col] = gl_obj[col].astype('category')
    else:
        converted_obj.loc[:,col] = gl_obj[col]
```

**Comment by danielhrisca** [comment] 2019-04-08 08:11
@Nimi42 

good idea, please check if the latest development code works as intended

**Comment by danielhrisca** [comment] 2019-04-08 16:35
> I will implement something similar to the new _resample_ method for _to_dataframe_ as well https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.resample

Now you can use an arbitrary array or a channel's timestamps as raster in the _to_dataframe_ (see [_to_dataframe_ documentation](https://asammdf.readthedocs.io/en/development/api.html#asammdf.mdf.MDF.to_dataframe))

**Comment by danielhrisca** [comment] 2019-05-03 08:52
I think we can close this. re-open if necessary

**Closed by danielhrisca** 2019-05-03 08:52 UTC
Labels: enhancement

**Comment by danielhrisca** [comment] 2019-12-12 11:42
In the development branch (soon to be 5.15.0) I have implemented the method _iter_to_dataframe_ that can be used to yield pandas dataframes that should not exceed 200MB of RAM. 

The memory requirement is to have enough RAM for:
* the MDF object
* all master channel arrays
* the union of all the master channel arrays
* the yielded datfram (~200MB)

Please try it out and see if works correctly.

**Comment by ronitch** [comment] 2022-06-01 14:50
> @Nimi42 
> 
> Thanks guys. I probably shouldn't use the thread to do this, but I just wanted to thank you for you help. I 've played around with your suggestions and have now a reliable way to convert large dat files to parquet.

Hi! Could you please share the code with me? It will be extremely helpful. Thanks!

**Comment by hongmofangjay** [comment] 2024-04-15 00:41
> I should note that it is necessary to Change asammdf library Code to accept your own time base. I posted the Code here but I felt like it was to much for this thread so ive deleted it again. You can message me if necessary. Cheers

Please share your code with me! The memory expands four times when I convert mf4 files. I need your hints. Thank you
